# Generated by Django 6.0.6 on 2026-07-08 09:48

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('accroche', models.CharField(blank=True, help_text='Affichée sous le titre dans la bannière, en capitales.', max_length=255, verbose_name='Accroche')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Pitch de la compagnie à destination des programmateur·ice·s, affiché sous la bannière.', verbose_name='Introduction')),
                ('atouts_titre', models.CharField(default="Pourquoi programmer la tribu d'Oya ?", max_length=255, verbose_name='Titre de la section atouts')),
                ('spectacles_titre', models.CharField(default='Nos spectacles disponibles à la programmation', max_length=255, verbose_name='Titre de la section spectacles')),
                ('infos_pratiques', wagtail.fields.RichTextField(blank=True, help_text="Conditions d'accueil, fiche technique, jauge, tarifs… Affiché après la liste des spectacles.", verbose_name='Informations pratiques')),
                ('cta_titre', models.CharField(default="Vous souhaitez programmer l'un de nos spectacles ?", max_length=255, verbose_name="Titre de l'appel à contact")),
                ('cta_texte', wagtail.fields.RichTextField(blank=True, help_text='Affiché sous le titre, au-dessus du bouton vers la page contact.', verbose_name="Texte de l'appel à contact")),
                ('background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image de fond')),
            ],
            options={
                'verbose_name': 'Page professionnels',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProAtout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('texte', models.TextField(blank=True, verbose_name='Texte')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='atouts', to='pros.propage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
