# Generated by Django 6.0.6 on 2026-06-20 11:00

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': "Page d'accueil"},
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Texte de présentation lu par les moteurs de recherche.', verbose_name='Texte de présentation (SEO)'),
        ),
    ]
