# Generated by Django 6.0.6 on 2026-07-03 13:15

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_options_homepage_intro'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Sous-titre')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Description')),
                ('button_text', models.CharField(blank=True, default='En savoir plus', max_length=100, verbose_name='Texte du bouton')),
                ('background_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image de fond')),
                ('link_page', models.ForeignKey(blank=True, help_text='Page du site vers laquelle pointe le bouton.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Page liée par le bouton')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_items', to='home.homepage')),
            ],
            options={
                'verbose_name': 'Item du carrousel',
                'verbose_name_plural': 'Items du carrousel',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
