# Generated by Django 6.0.6 on 2026-07-03 13:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_custom_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='custom_section',
            field=wagtail.fields.StreamField([('heading', 1), ('paragraph', 2), ('image', 5), ('button', 9), ('interactive_list', 17), ('separator', 19), ('columns', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Texte du titre', 'max_length': 255}), 1: ('wagtail.blocks.StructBlock', [[('text', 0)]], {}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'link', 'h3', 'h4'], 'icon': 'pilcrow', 'label': 'Texte riche', 'template': 'home/blocks/paragraph_block.html'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Légende', 'max_length': 255, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 3), ('caption', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Libellé', 'max_length': 80}), 7: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Page du site visée par le bouton (prioritaire sur le lien externe).', 'label': 'Lien vers une page', 'required': False}), 8: ('wagtail.blocks.URLBlock', (), {'help_text': "Utilisé seulement si aucune page n'est choisie ci-dessus.", 'label': 'Lien externe', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('text', 6), ('link_page', 7), ('url', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'label': 'Titre', 'max_length': 120}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Sous-titre', 'max_length': 200, 'required': False}), 12: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'link', 'h3', 'h4'], 'label': 'Contenu détaillé', 'required': False}), 13: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': "Optionnel : s'affiche dans le volet de droite au survol de l'item (sous le titre sur mobile).", 'label': 'Image', 'required': False}), 14: ('wagtail.blocks.PageChooserBlock', (), {'help_text': "Optionnel : rend l'item cliquable vers cette page du site.", 'label': 'Lien vers une page', 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('title', 10), ('subtitle', 11), ('content', 12), ('image', 13), ('link_page', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {'label': 'Items', 'min_num': 1}), 17: ('wagtail.blocks.StructBlock', [[('items', 16)]], {}), 18: ('wagtail.blocks.FloatBlock', (), {'default': 2, 'help_text': "Hauteur de l'espace vide, en rem (1 rem ≈ 16 px).", 'label': 'Hauteur (rem)', 'min_value': 0}), 19: ('wagtail.blocks.StructBlock', [[('height', 18)]], {}), 20: ('wagtail.blocks.StreamBlock', [[('heading', 1), ('paragraph', 2), ('image', 5), ('button', 9), ('interactive_list', 17), ('separator', 19)]], {}), 21: ('wagtail.blocks.ListBlock', (20,), {'help_text': "Ajoutez de 2 à 4 colonnes ; elles s'empilent sur mobile.", 'label': 'Colonnes', 'max_num': 4, 'min_num': 2}), 22: ('wagtail.blocks.StructBlock', [[('columns', 21)]], {})}, help_text='Contenu libre affiché sous le carrousel.', verbose_name='Section personnalisable'),
        ),
    ]
