# Generated by Django 6.0.6 on 2026-07-03 14:10

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homepage_custom_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='custom_section',
            field=wagtail.fields.StreamField([('heading', 1), ('paragraph', 4), ('image', 7), ('button', 12), ('interactive_list', 20), ('separator', 22), ('columns', 25)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Texte du titre', 'max_length': 255}), 1: ('wagtail.blocks.StructBlock', [[('text', 0)]], {}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'link', 'h3', 'h4'], 'label': 'Texte'}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('sm', 'Petit'), ('base', 'Normal'), ('lg', 'Grand'), ('xl', 'Très grand')], 'label': 'Taille du texte'}), 4: ('wagtail.blocks.StructBlock', [[('text', 2), ('size', 3)]], {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 6: ('wagtail.blocks.CharBlock', (), {'label': 'Légende', 'max_length': 255, 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 5), ('caption', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Libellé', 'max_length': 80}), 9: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Page du site visée par le bouton (prioritaire sur le lien externe).', 'label': 'Lien vers une page', 'required': False}), 10: ('wagtail.blocks.URLBlock', (), {'help_text': "Utilisé seulement si aucune page n'est choisie ci-dessus.", 'label': 'Lien externe', 'required': False}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('sm', 'Petit'), ('base', 'Normal'), ('lg', 'Grand'), ('xl', 'Très grand')], 'label': 'Taille du bouton'}), 12: ('wagtail.blocks.StructBlock', [[('text', 8), ('link_page', 9), ('url', 10), ('size', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'label': 'Titre', 'max_length': 120}), 14: ('wagtail.blocks.CharBlock', (), {'label': 'Sous-titre', 'max_length': 200, 'required': False}), 15: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'ol', 'ul', 'link', 'h3', 'h4'], 'label': 'Contenu détaillé', 'required': False}), 16: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': "Optionnel : s'affiche dans le volet de droite au survol de l'item (sous le titre sur mobile).", 'label': 'Image', 'required': False}), 17: ('wagtail.blocks.PageChooserBlock', (), {'help_text': "Optionnel : rend l'item cliquable vers cette page du site.", 'label': 'Lien vers une page', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('title', 13), ('subtitle', 14), ('content', 15), ('image', 16), ('link_page', 17)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {'label': 'Items', 'min_num': 1}), 20: ('wagtail.blocks.StructBlock', [[('items', 19)]], {}), 21: ('wagtail.blocks.FloatBlock', (), {'default': 2, 'help_text': "Hauteur de l'espace vide, en rem (1 rem ≈ 16 px).", 'label': 'Hauteur (rem)', 'min_value': 0}), 22: ('wagtail.blocks.StructBlock', [[('height', 21)]], {}), 23: ('wagtail.blocks.StreamBlock', [[('heading', 1), ('paragraph', 4), ('image', 7), ('button', 12), ('interactive_list', 20), ('separator', 22)]], {}), 24: ('wagtail.blocks.ListBlock', (23,), {'help_text': "Ajoutez de 2 à 4 colonnes ; elles s'empilent sur mobile.", 'label': 'Colonnes', 'max_num': 4, 'min_num': 2}), 25: ('wagtail.blocks.StructBlock', [[('columns', 24)]], {})}, help_text='Contenu libre affiché sous le carrousel.', verbose_name='Section personnalisable'),
        ),
    ]
