# Generated by Django 6.0.6 on 2026-06-20 11:00

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Page index des stages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StagePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('type', models.CharField(blank=True, default='Stage de théâtre', max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('credit', wagtail.fields.RichTextField(blank=True, verbose_name='Crédits')),
                ('description_courte', models.CharField(blank=True, max_length=255, verbose_name='Description courte')),
                ('intention', wagtail.fields.RichTextField(blank=True)),
                ('theme', wagtail.fields.RichTextField(blank=True, verbose_name='Thème')),
                ('note', wagtail.fields.RichTextField(blank=True)),
                ('youtube_link', models.URLField(blank=True, help_text="URL d'intégration, ex: https://www.youtube.com/embed/XXXX", verbose_name='Lien YouTube (embed)')),
                ('background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image de fond')),
            ],
            options={
                'verbose_name': 'Stage / Atelier',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StageObjectif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('texte', models.CharField(max_length=500)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs', to='stages.stagepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StageDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('date', models.CharField(max_length=255)),
                ('horaires', models.CharField(blank=True, max_length=255)),
                ('lieu', models.CharField(blank=True, max_length=255)),
                ('billetterie', models.URLField(blank=True, verbose_name='Lien billetterie')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='prochaines_dates', to='stages.stagepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StageAxeTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('texte', models.CharField(max_length=500)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='axes_travail', to='stages.stagepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
