# Generated by Django 6.0.6 on 2026-06-20 11:00

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Page index des projets',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjetPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, default='Pièce de théâtre', max_length=255)),
                ('annee', models.CharField(blank=True, max_length=50, verbose_name='Année de création')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('credit', wagtail.fields.RichTextField(blank=True, verbose_name='Crédits')),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('youtube_link', models.URLField(blank=True, help_text="URL d'intégration, ex: https://www.youtube.com/embed/XXXX", verbose_name='Lien YouTube (embed)')),
                ('is_in_progress', models.BooleanField(default=False, help_text="Si coché, le projet s'affiche sans page de détail (badge « En cours de création »).", verbose_name='En cours de création')),
                ('background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image de fond')),
                ('press_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Dossier de presse')),
            ],
            options={
                'verbose_name': 'Projet / Spectacle',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjetGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='projets.projetpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
