# Generated by Django 6.0.6 on 2026-07-06 09:41

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetpage',
            name='dossier_artistique_url',
            field=models.URLField(blank=True, help_text='Lien externe vers le dossier artistique (affiché sous la description dans la bannière).', verbose_name='Lien dossier artistique'),
        ),
        migrations.CreateModel(
            name='ProjetRepresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('date', models.CharField(max_length=255)),
                ('lieu', models.CharField(blank=True, max_length=255)),
                ('billetterie', models.URLField(blank=True, verbose_name='Lien billetterie')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='representations', to='projets.projetpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
