# Generated by Django 6.0.6 on 2026-07-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0003_projetacteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetacteur',
            name='copyright',
            field=models.CharField(blank=True, help_text='Affiché en surimpression de la photo (ex. « © Nom du photographe »).', max_length=255, verbose_name='Copyright / crédit photo'),
        ),
    ]
