# Generated by Django 6.0.6 on 2026-07-06 10:28

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0004_projetacteur_copyright'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetpage',
            name='infos_complementaires',
            field=wagtail.fields.RichTextField(blank=True, help_text='Bloc de texte riche affiché en bas de la page.', verbose_name='Informations complémentaires'),
        ),
    ]
