# Generated by Django 6.0.6 on 2026-07-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0005_projetpage_infos_complementaires'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetrepresentation',
            name='horaire',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
