# Generated by Django 6.0.6 on 2026-07-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0006_projetrepresentation_horaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetpage',
            name='youtube_link',
            field=models.URLField(blank=True, help_text="Colle n'importe quel lien YouTube (youtu.be, watch?v=, shorts ou embed) : il est converti automatiquement pour l'intégration.", verbose_name='Lien YouTube'),
        ),
    ]
