# Generated by Django 6.0.6 on 2026-07-08 07:41

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0007_alter_projetpage_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetacteur',
            name='role',
            field=models.CharField(blank=True, help_text='Affiché sous le nom dans la distribution.', max_length=255, verbose_name='Rôle joué'),
        ),
        migrations.AlterField(
            model_name='projetpage',
            name='infos_complementaires',
            field=wagtail.fields.RichTextField(blank=True, help_text='Texte de présentation affiché sous le teaser, dans la colonne principale de la page.', verbose_name='Présentation du spectacle'),
        ),
    ]
