# Generated by Django 6.0.6 on 2026-06-20 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReseauxPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('newsletter_url', models.URLField(blank=True, default='https://docs.google.com/forms/d/e/1FAIpQLSewSgWZY9YDsHSC18c_kRbG-TqAj5YUsXkmHbkRxm8cYNgFUg/viewform?usp=header', verbose_name='Lien newsletter')),
                ('facebook_url', models.URLField(blank=True, default='https://www.facebook.com/latribudoya', verbose_name='Lien Facebook')),
                ('instagram_url', models.URLField(blank=True, default='https://www.instagram.com/latribudoya/', verbose_name='Lien Instagram')),
                ('helloasso_url', models.URLField(blank=True, default='https://www.helloasso.com/associations/la-tribu-d-oya', verbose_name='Lien HelloAsso')),
            ],
            options={
                'verbose_name': 'Page réseaux sociaux',
            },
            bases=('wagtailcore.page',),
        ),
    ]
